export const TYPES = {
    SET_USER: 'SET_USER',
    SET_PLAYING: 'SET_PLAYING',
    SET_ITEM: 'SET_ITEM',
    SET_DISCOVER_WEEKLY: 'SET_DISCOVER_WEEKLY',
    SET_TOP_ARTISTS: 'SET_TOP_ARTISTS',
    SET_TOKEN: 'SET_TOKEN',
    SET_SPOTIFY: 'SET_SPOTIFY',
    SET_PLAYLISTS: 'SET_PLAYLISTS',
}